### ISSUE TITLE
Need help in running the SimpleSSD

### ISSUE THREAD

**Issue by kimbob13** [SimpleSSD/SimpleSSD-FullSystem#2]
Hi, I would like to build and run SimpleSSD-FullSystem , so I follow instruction in your website (especially in [this site](https://simplessd.org/fs.html) )
I cloned this repository, and when I try to run, I encountered some problem.

1. When building the linux kernel, your [website](https://simplessd.org/build_kernel.html) says nothing about kernel configuration, but only make menuconfig. Is it OK to use just default configuration?
Or, there is anything to change to work properly?

2. Also, I don't understand about Build Module section in build kernel page, especially, what are the necessary external module? Could you please elaborate on this? 
Next, how can I create x86root.img file? I want to know which is needed for creating x86root.img file.

3. I think there is no explanation about addning new debug-flag options.
So, I saw an error that it can't find FTLOut and PAL2 options.
I want to know how to add these options in debug-flag.

4. And I found some errors in your source code. 
    - First, when building the gem5, there is an error in [src/dev/x86/i8042.cc - 401 lines](https://github.com/SimpleSSD/SimpleSSD-FullSystem/blob/86f6da35424156eb17cf0e6d29a67a480b9097bc/src/dev/x86/i8042.cc#L401). There is an duplicated case statement, so I just commented out and compiled.

    - Second, because of #3 issues, I just tried to run gem5 without debug-flag options. But, it also has an error in [configs/common/FSConfig.py - 677 lines](https://github.com/SimpleSSD/SimpleSSD-FullSystem/blob/86f6da35424156eb17cf0e6d29a67a480b9097bc/configs/common/FSConfig.py#L677). It was argument ordering error, so I changed order of simplessd and numCPUs.

    - So I want to know about any errors other than this, so that SimpleSSD works properly.

Thank you for your hard work!
I'm looking forward to hearing from you.

**Comment by kukdh1** [comment]
Hi,

> 1. Building X86 kernel.

X86 gem5 executes x86_64 kernel with default configurations, as I remember.
But you want to ensure following modules are enabled:
```
Device Drivers > Serial ATA and Parallel ATA drivers (libata) > Intel PATA old PIIX support
Device Drivers > NVM Express block device
```
Note. We recommend you to use ARM gem5.

> 2. Kernel modules

You may want to search about building Linux Kernel from Source.
If you configured kernel to build all modules to be 'built-in', you don't need to build modules.
In the configuration page, `[*]` or `<*>` means 'built-in', `<M>` means 'module'.

> 3.  Disk image

gem5 has [instruction](http://gem5.org/Using_linux-dist_to_Create_Disk_Images_and_Kernels_for_M5) for creating disk image, but this document is too old.
Check [here](http://www.lowepower.com/jason/creating-disk-images-for-gem5.html) instead.

> 4. Errors.

The bugs that you mentioned here are already fixed in our internal version.
SimpleSSD should executed without error.

Note 1. SimpleSSD instruction in our [homepage](simplessd.org) is outdated (for  v1.0).
Note 2. SimpleSSD instruction for v2.x will be appear in 한국정보과학회지 6월호, written in Korean.

Thanks.

**Comment by kimbob13** [comment]
Thank you for your answer.
Then, I want to know when your internal version is uploaded to github.

Thanks!
