### ISSUE TITLE
Is embedded CPU currently possible ?

### ISSUE THREAD

**Issue by qwunmd** [SimpleSSD/SimpleSSD-FullSystem#24]
Hi ,

I'm trying to use Amber to simulate in-storage computing , but there is nothing about embedded CPU in the documentation website .

So can I use Amber to simualte a CPU or  FPGAs inside SSD ?

Thanks.

**Comment by kukdh1** [comment]
Hi,

SimpleSSD 2.0 (Amber) only includes static firmware latency, which is calculated at compilation phase (hard coded in [`src/dev/storage/simplessd/cpu/cpu.cc`](https://github.com/SimpleSSD/SimpleSSD/blob/2.0/cpu/cpu.cc#L138)).
SimpleSSD 2.1 (not yet in public) has dynamic firmware latency, but this one is based on LLVM, not a real CPU model.
Currently, I have no plan to add real CPU model (like gem5) in near feature (because of the simulation speed).

If you want to use SimpleSSD for ISP, you need to modify SimpleSSD to have latency model of arbitrary code execution (CPU) or cycles (FPGA).
Find appropriate position to add computation model and add calculated latency to `tick` variable.

P.S. I recommend to use standalone version if your research does not require host intervention.

Thanks.
