### ISSUE TITLE
How to install programs in the simpleSSD?

### ISSUE THREAD

**Issue by somnode** [SimpleSSD/SimpleSSD-FullSystem#4]
Hi, 

The OC-SSD device is finally captured when I typing following command: `./nvme list`.
I would like to do a `git clone`, but there cannot be done `apt-get`, and downloading a program with `wget` also cannot be done because of the network problem.

So, how to create a target?

**Comment by kukdh1** [comment]
Hi,

gem5 does not support internet connection with host machine (because of timing differences).
You must compile all the programs/libraries on host machine (using cross-compiler, if you use ARM), and copy it to the disk image (e.g., `linux-aarch64-linux.img`).

To create `pblk` target, use following commands inside the gem5.
```shell
# You can find total number of LUN in nvm notation
# e.g., nvm notation (old): [8/1/512/512/64/8] -> 5th number (64) is total LUN
# e.g., nvm notation (new): [8/8/512/64/8] -> 4th number (64) is total LUN
nvme lnvm create -d nvme0n1 -n lnvm0 -t pblk -b 0 -e 63
# -d : identifier of desired device
# -n : target name of the device to initialize
# -t : identifier of target type
# -b : begin of LUNs to use
# -e : end of LUNs to use (here, 63 = 64 - 1)
```
This will create block device named `/dev/lnvm0`.

Thanks.

**Comment by qjyimyy** [comment]
hello，how can i solve the problem that can't find the type of pblk

**Comment by qjyimyy** [comment]
hello，how can i solve the problem that can't find the type of pblk

If i use 'sudo nvme lnvm info' , there is no target type registered. So I can't create pblk target.
